FROM registry.access.redhat.com/ubi9/python-39:latest@sha256:a49364adae4cd27b1b4c469174f9bd4988ea4191c4dcb7da5a2d44513e590ba7

LABEL maintainer="Red Hat - EXD"

WORKDIR /src

# Switch to privileged user to install dependencies and application
USER 0

# copy config
COPY ./conf/app.conf /etc/ubi_manifest/app.conf

# add certs for trusted connection dependent services if required
COPY ./conf/certs/* /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust extract

# Let poetry use the virtualenv that comes with the base image
ENV POETRY_VIRTUALENVS_CREATE=false
# Path to the virtualenv from base image
ENV VIRTUAL_ENV=${APP_ROOT}
# Add os-level module to PYTHONPATH so we can use rpm module
ENV PYTHONPATH="${PYTHONPATH}:/usr/lib64/python3.9/site-packages"

COPY . .

RUN pip install --upgrade pip
# install poetry
RUN pip install poetry

RUN poetry install

# Switch back to unprivileged user to run the application
USER 1001


CMD celery -A ubi_manifest.worker.tasks beat --loglevel=debug -s ${APP_ROOT}/celerybeat-schedule
