FROM registry.access.redhat.com/ubi9/python-39:latest

LABEL maintainer="Red Hat - EXD"

WORKDIR /src

# Switch to priviledged user to install dependencies and application
USER 0

# copy config
COPY ./conf/app.conf /etc/ubi_manifest/app.conf

ENV POETRY_VERSION="1.7.0"\
    # Let poetry use the virtualenv that comes with the base image
    POETRY_VIRTUALENVS_CREATE=false\
    # Path to the virtualenv from base image
    VIRTUAL_ENV=${APP_ROOT}\
    # Add os-level module to PYTHONPATH so we can use rpm module
    PYTHONPATH="${PYTHONPATH}:/usr/lib64/python3.9/site-packages"

COPY . .

# install poetry
RUN pip install poetry

RUN poetry install --with server

# Switch back to unpriviledged user to run the application
USER 1001

EXPOSE 8000

CMD ["gunicorn", "--worker-class", "uvicorn.workers.UvicornWorker", "-w 4", "--config", "/src/conf/gunicorn.conf", "ubi_manifest.app.factory:create_app()"]
