FROM registry.access.redhat.com/ubi8/python-39

LABEL maintainer="Red Hat - EXD"

WORKDIR /src

# Switch to priviledged user to install dependencies and application
USER 0

# Enable CentOS repos, as rpm-devel is not in RHEL repos
COPY ./docker/rpm-config/CentOS-Stream-rhsrvany.repo /etc/yum.repos.d/
COPY ./docker/rpm-config/RPM-GPG-KEY-centosofficial /etc/pki/rpm-gpg/

RUN yum repolist
RUN yum install -y --disableplugin=subscription-manager rpm-devel

# copy config
COPY ./conf/app.conf /etc/ubi_manifest/app.conf

ENV POETRY_VERSION="1.7.0"\
    # Let poetry use the virtualenv that comes with the base image
    POETRY_VIRTUALENVS_CREATE=false\
    # Path to the virtualenv from base image
    VIRTUAL_ENV=${APP_ROOT}

COPY . .

# install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

RUN poetry install --with server


# Switch back to unpriviledged user to run the application
USER 1001

EXPOSE 8000

CMD ["gunicorn", "--worker-class", "uvicorn.workers.UvicornWorker", "-w 4", "--config", "/src/conf/gunicorn.conf", "ubi_manifest.app.factory:create_app()"]
