FROM registry.access.redhat.com/ubi8/python-39

LABEL maintainer="Red Hat - EXD"

WORKDIR /src

# Switch to priviledged user to install rpm-devel
USER 0

# Enable CentOS repos, as rpm-devel is not in RHEL repos
COPY ./docker/rpm-config/CentOS-Stream-rhsrvany.repo /etc/yum.repos.d/
COPY ./docker/rpm-config/RPM-GPG-KEY-centosofficial /etc/pki/rpm-gpg/

RUN yum repolist
RUN yum install -y --disableplugin=subscription-manager rpm-devel

# Switch back to unpriviledged user
USER 1001

COPY . .

RUN pip3 install .

CMD celery -A ubi_manifest.worker.tasks worker --loglevel=debug
