FROM registry.access.redhat.com/ubi9/python-39:latest@sha256:822a0c1b758a1d4c4344f50ae2dbcf5df3b7b880cf1e35c43a3a3d1cce764318

LABEL maintainer="Red Hat - EXD"

WORKDIR /src

# Switch to privileged user to install dependencies and application
USER 0

# copy config
COPY ./conf/app.conf /etc/ubi_manifest/app.conf

# add certs for trusted connection dependent services if required
COPY ./conf/certs/* /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust extract

# Let poetry use the virtualenv that comes with the base image
ENV POETRY_VIRTUALENVS_CREATE=false
# Path to the virtualenv from base image
ENV VIRTUAL_ENV=${APP_ROOT}
# Add os-level module to PYTHONPATH so we can use rpm module
ENV PYTHONPATH="${PYTHONPATH}:/usr/lib64/python3.9/site-packages"

COPY . .

RUN pip install --upgrade pip
# install poetry
RUN pip install poetry

RUN poetry install --with server

# Switch back to unprivileged user to run the application
USER 1001

EXPOSE 8000

CMD ["gunicorn", "ubi_manifest.app.factory:create_app()", "--config", "/src/conf/gunicorn_conf.py"]
