#!/usr/bin/env python3
# Helper script to generate openapi JSON file
# during publishing of docs.
import os
import json
import shutil


from ubi_manifest.app.factory import create_app

api = create_app().openapi()

with open("docs/openapi/openapi.json", "wt") as f:
    json.dump(api, f)

for f in os.listdir("docs/openapi"):
    shutil.copy("docs/openapi/" + f, "docs/_build/html")
